import type {
  ActivityEvent,
  AgentMessage,
  Machine,
  Project,
} from "@orbit/shared";

export const projects: Project[] = [
  {
    id: "trace",
    name: "Trace",
    description: "Product engineering and infrastructure workspace",
    machineCount: 3,
    updatedAt: "2026-09-03T02:42:00.000Z",
  },
  {
    id: "grasp",
    name: "Grasp",
    description: "Research prototypes and evaluation environments",
    machineCount: 2,
    updatedAt: "2026-09-02T18:10:00.000Z",
  },
  {
    id: "personal",
    name: "Personal",
    description: "Private experiments and utility machines",
    machineCount: 1,
    updatedAt: "2026-08-31T09:24:00.000Z",
  },
];

export const machines: Machine[] = [
  {
    id: "ubuntu-dev",
    projectId: "trace",
    name: "Ubuntu Dev",
    os: "ubuntu",
    osLabel: "Ubuntu 24.04",
    status: "running",
    cpu: 4,
    ramGb: 8,
    storageGb: 80,
    lastSeenAt: "2026-09-03T03:20:00.000Z",
  },
  {
    id: "windows-qa",
    projectId: "trace",
    name: "Windows QA",
    os: "windows",
    osLabel: "Windows 11",
    status: "stopped",
    cpu: 4,
    ramGb: 8,
    storageGb: 80,
    lastSeenAt: "2026-09-02T21:04:00.000Z",
  },
  {
    id: "mac-build",
    projectId: "trace",
    name: "Mac Build",
    os: "macos",
    osLabel: "macOS",
    status: "stopped",
    cpu: 8,
    ramGb: 16,
    storageGb: 120,
    lastSeenAt: "2026-09-01T16:18:00.000Z",
  },
  {
    id: "grasp-linux",
    projectId: "grasp",
    name: "Eval Runner",
    os: "ubuntu",
    osLabel: "Ubuntu 24.04",
    status: "running",
    cpu: 8,
    ramGb: 16,
    storageGb: 120,
    lastSeenAt: "2026-09-03T03:18:00.000Z",
  },
  {
    id: "grasp-windows",
    projectId: "grasp",
    name: "Browser Lab",
    os: "windows",
    osLabel: "Windows 11",
    status: "stopped",
    cpu: 4,
    ramGb: 8,
    storageGb: 80,
    lastSeenAt: "2026-09-02T12:30:00.000Z",
  },
  {
    id: "personal-mac",
    projectId: "personal",
    name: "Personal Mac",
    os: "macos",
    osLabel: "macOS",
    status: "stopped",
    cpu: 4,
    ramGb: 8,
    storageGb: 80,
    lastSeenAt: "2026-08-31T09:24:00.000Z",
  },
];

export const activity: ActivityEvent[] = [
  {
    id: "activity-1",
    projectId: "trace",
    machineId: "ubuntu-dev",
    type: "agent",
    title: "Editing src/index.ts",
    detail: "Agent updated the workspace entry point",
    timestamp: "2026-09-03T03:19:40.000Z",
  },
  {
    id: "activity-2",
    projectId: "trace",
    machineId: "ubuntu-dev",
    type: "agent",
    title: "Running pnpm install",
    detail: "Installed 24 workspace dependencies",
    timestamp: "2026-09-03T03:18:12.000Z",
  },
  {
    id: "activity-3",
    projectId: "trace",
    machineId: "ubuntu-dev",
    type: "machine",
    title: "Opening Terminal",
    detail: "Terminal opened on Ubuntu Dev",
    timestamp: "2026-09-03T03:17:26.000Z",
  },
  {
    id: "activity-4",
    projectId: "grasp",
    machineId: "grasp-linux",
    type: "system",
    title: "Machine resumed",
    detail: "Eval Runner is ready",
    timestamp: "2026-09-03T01:10:00.000Z",
  },
  {
    id: "activity-5",
    projectId: "personal",
    machineId: "personal-mac",
    type: "file",
    title: "Files synchronized",
    detail: "12 files updated",
    timestamp: "2026-08-31T09:24:00.000Z",
  },
];

export const messages: AgentMessage[] = [
  {
    id: "message-1",
    projectId: "trace",
    machineId: "ubuntu-dev",
    role: "user",
    content: "Prepare the Trace release. Run the test suite, review the open returns in the admin, and stage the desktop build. Use separate computers where it helps.",
    timestamp: "2026-09-03T03:16:52.000Z",
  },
  {
    id: "message-2",
    projectId: "trace",
    machineId: "ubuntu-dev",
    role: "assistant",
    content: "I split the work across the fleet: Ubuntu Dev is running the suite, Windows QA is checking the returns flow in-browser, and Mac Build is preparing the signed artifact.",
    timestamp: "2026-09-03T03:17:04.000Z",
  },
  {
    id: "message-3",
    projectId: "trace",
    machineId: "ubuntu-dev",
    role: "assistant",
    content: "The checks are clean. I found one eligible return and have the approval ready on screen. The release artifact is building now; I’ll keep the computers attached until you review it.",
    timestamp: "2026-09-03T03:19:44.000Z",
  },
  {
    id: "message-4",
    projectId: "grasp",
    machineId: "grasp-linux",
    role: "assistant",
    content: "Eval Runner is online and waiting for a task.",
    timestamp: "2026-09-03T01:11:00.000Z",
  },
  {
    id: "message-5",
    projectId: "personal",
    machineId: "personal-mac",
    role: "assistant",
    content: "This workspace is ready when you are.",
    timestamp: "2026-08-31T09:25:00.000Z",
  },
];
