// Keep icon imports centralized and path-specific. Phosphor's root barrel exposes
// thousands of icons; direct entry points keep Vite's module graph focused.
export { AppleLogo } from "@phosphor-icons/react/AppleLogo";
export { ArrowClockwise } from "@phosphor-icons/react/ArrowClockwise";
export { ArrowLeft } from "@phosphor-icons/react/ArrowLeft";
export { ArrowRight } from "@phosphor-icons/react/ArrowRight";
export { ArrowUp } from "@phosphor-icons/react/ArrowUp";
export { ArrowUpRight } from "@phosphor-icons/react/ArrowUpRight";
export { ArrowsClockwise } from "@phosphor-icons/react/ArrowsClockwise";
export { Bell } from "@phosphor-icons/react/Bell";
export { Buildings } from "@phosphor-icons/react/Buildings";
export { CaretDown } from "@phosphor-icons/react/CaretDown";
export { CaretRight } from "@phosphor-icons/react/CaretRight";
export { ChatCircleDots } from "@phosphor-icons/react/ChatCircleDots";
export { Check } from "@phosphor-icons/react/Check";
export { Circle } from "@phosphor-icons/react/Circle";
export { CircleNotch } from "@phosphor-icons/react/CircleNotch";
export { Clock } from "@phosphor-icons/react/Clock";
export { Code } from "@phosphor-icons/react/Code";
export { Command } from "@phosphor-icons/react/Command";
export { Cpu } from "@phosphor-icons/react/Cpu";
export { Cube } from "@phosphor-icons/react/Cube";
export { Cursor } from "@phosphor-icons/react/Cursor";
export { Database } from "@phosphor-icons/react/Database";
export { DesktopTower } from "@phosphor-icons/react/DesktopTower";
export { DotsThree } from "@phosphor-icons/react/DotsThree";
export { FileText } from "@phosphor-icons/react/FileText";
export { Flask } from "@phosphor-icons/react/Flask";
export { Folder } from "@phosphor-icons/react/Folder";
export { FolderOpen } from "@phosphor-icons/react/FolderOpen";
export { Gauge } from "@phosphor-icons/react/Gauge";
export { Gear } from "@phosphor-icons/react/Gear";
export { GitPullRequest } from "@phosphor-icons/react/GitPullRequest";
export { Globe } from "@phosphor-icons/react/Globe";
export { GridFour } from "@phosphor-icons/react/GridFour";
export { HardDrive } from "@phosphor-icons/react/HardDrive";
export { HardDrives } from "@phosphor-icons/react/HardDrives";
export { Keyboard } from "@phosphor-icons/react/Keyboard";
export { Laptop } from "@phosphor-icons/react/Laptop";
export { Lock } from "@phosphor-icons/react/Lock";
export { MagnifyingGlass } from "@phosphor-icons/react/MagnifyingGlass";
export { Memory } from "@phosphor-icons/react/Memory";
export { Microphone } from "@phosphor-icons/react/Microphone";
export { Monitor } from "@phosphor-icons/react/Monitor";
export { Package } from "@phosphor-icons/react/Package";
export { Plus } from "@phosphor-icons/react/Plus";
export { Question } from "@phosphor-icons/react/Question";
export { Robot } from "@phosphor-icons/react/Robot";
export { ShareNetwork } from "@phosphor-icons/react/ShareNetwork";
export { ShieldCheck } from "@phosphor-icons/react/ShieldCheck";
export { ShieldCheckered } from "@phosphor-icons/react/ShieldCheckered";
export { SidebarSimple } from "@phosphor-icons/react/SidebarSimple";
export { SignOut } from "@phosphor-icons/react/SignOut";
export { Sparkle } from "@phosphor-icons/react/Sparkle";
export { SquaresFour } from "@phosphor-icons/react/SquaresFour";
export { Terminal } from "@phosphor-icons/react/Terminal";
export { TerminalWindow } from "@phosphor-icons/react/TerminalWindow";
export { UserCircle } from "@phosphor-icons/react/UserCircle";
export { WarningCircle } from "@phosphor-icons/react/WarningCircle";
export { X } from "@phosphor-icons/react/X";

// Lucide is a fallback for specific shapes only. Keep Phosphor as the default;
// add explicit named exports here instead of importing the whole icon library.
export { SquarePen } from "lucide-react";

export { DownloadSimple } from "@phosphor-icons/react/DownloadSimple";
